// 路由映射为请求参数对象
export default {
  'teacher-board':'teacherExchange',
  "overseas-expert-exchange":"longtermExpert",
  "overseas-expert-exchange-short":"shorttermExpert",
  "internation-publication":"publicationJob",
  "overseas-expert-part-time":"expertJob",
  "overseas-expert-prize":"expertAward",
  "student-board":"studentExchange",
  "internation-student-education":"iternationalStudentEdu",
  "open-internation-course":"itCourse",
  "overseas-education":"cooperativeeducation",
  "student-exchange":"stuExchangeProject",
  "internation-research":"itResearchPlatform",
  "internation-result":"itAchievementTrainingPlatform",
  "internation-area":"nationalRegionalCenter",
  "advanced-expert":"expertIntroPlan",
  "advanced-project-import":"introWiseProject",
  "internation-research-meeting":"itMeeting",
  "internation-guarantee":"itGuaranteeFeature",
  "overseas-treaty":"exchangeCooperation",
  "interation-ally":"leagueNations",
}